apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- if .Values.global.isGDC }}
  annotations:
    networking.istio.io/exportTo: "., asm-gateway"
  {{- end }}
spec:
  selector:
    app: {{ $.Release.Name }}
  ports:
    - protocol: TCP
      name: http
      port: 8080
    {{- if .Values.global.isGDC }}
    - name: web
      port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
    {{- end }}
  type: {{ .Values.service.type }}